using System.Net;
using System.Text;
using AeroTravel.Application.Common.Interfaces;
using AeroTravel.Application.Common.Models;
using AeroTravel.Application.Features.TravelRequests.Dtos;
using AeroTravel.Domain.Entities;
using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace AeroTravel.Application.Features.TravelRequests.Commands;

// Public lead-capture endpoint. Anti-spam per DEC-004: a honeypot field ("website") that real
// users never see/fill; bots that autofill every field trip it. We reject rather than
// silently-drop so the frontend can show a generic error without a fake "success" response
// that would make client-side debugging confusing; the field is invisible to humans anyway.
public record CreateTravelRequestCommand(CreateTravelRequestInput Input, string? SourceIp) : IRequest<Result<Guid>>;

public class CreateTravelRequestCommandValidator : AbstractValidator<CreateTravelRequestCommand>
{
    public const int MaxPassengers = 9;
    public const int MaxChildAge = 17;
    public const int MaxPassportPhotos = 1;

    public CreateTravelRequestCommandValidator(IFileStorageService fileStorage)
    {
        RuleFor(x => x.Input.LastName).NotEmpty().MaximumLength(200);
        RuleFor(x => x.Input.FirstName).NotEmpty().MaximumLength(200);
        RuleFor(x => x.Input.MiddleName).MaximumLength(200);

        // +992 (Tajikistan) fixed prefix, exactly 9 digits after it — mirrors the frontend's
        // fixed-prefix phone input, which only ever lets the user type the 9 trailing digits.
        RuleFor(x => x.Input.Phone).Matches(@"^\+992\d{9}$").WithMessage("Phone must be in the format +992XXXXXXXXX.");

        RuleFor(x => x.Input.PassengersAdults).InclusiveBetween(1, MaxPassengers);
        RuleFor(x => x.Input.PassengersChildren).InclusiveBetween(0, MaxPassengers);

        RuleFor(x => x.Input.ChildrenAges.Count)
            .Equal(x => x.Input.PassengersChildren)
            .WithMessage("The number of children's ages must match the number of children.");
        RuleForEach(x => x.Input.ChildrenAges).InclusiveBetween(0, MaxChildAge);

        RuleFor(x => x.Input.DepartureDate)
            .GreaterThanOrEqualTo(x => DateOnly.FromDateTime(DateTime.UtcNow))
            .WithMessage("Departure date cannot be in the past.");
        RuleFor(x => x.Input.ReturnDate)
            .GreaterThanOrEqualTo(x => x.Input.DepartureDate)
            .When(x => x.Input.ReturnDate is not null)
            .WithMessage("Return date cannot be before the departure date.");

        // Passport photos are the substance of the request — a passport is one page (the photo
        // spread), so exactly one photo, and verify the referenced file was actually uploaded
        // first (these filenames are server-generated by the upload endpoint, never client-chosen,
        // so this is also the point where a request referencing an unknown/already-consumed name
        // is rejected). Existing requests submitted with 2 photos before this change are untouched
        // — this only constrains new submissions.
        RuleFor(x => x.Input.PassportPhotoPaths.Count).Equal(MaxPassportPhotos)
            .WithMessage("Attach one international passport photo.");
        RuleForEach(x => x.Input.PassportPhotoPaths)
            .MustAsync(async (fileName, ct) => await fileStorage.ExistsAsync(fileName, ct))
            .WithMessage("One of the uploaded international passport photos could not be found — please re-upload it.");
        RuleFor(x => x.Input.PassportDataConsentAccepted).Equal(true)
            .WithMessage("Consent to process international passport/ID data is required.");

        RuleFor(x => x.Input.ConsentAccepted).Equal(true).WithMessage("Consent is required.");

        RuleFor(x => x.Input.Message).MaximumLength(500);
    }
}

public class CreateTravelRequestCommandHandler(
    IApplicationDbContext db,
    IEmailService emailService,
    IOptions<NotificationSettings> notificationSettings,
    ILogger<CreateTravelRequestCommandHandler> logger) : IRequestHandler<CreateTravelRequestCommand, Result<Guid>>
{
    public async Task<Result<Guid>> Handle(CreateTravelRequestCommand request, CancellationToken cancellationToken)
    {
        var input = request.Input;

        if (!string.IsNullOrWhiteSpace(input.Website))
            return Result.Failure<Guid>(Error.Validation("VALIDATION_FAILED", "Request could not be submitted."));

        string? destinationTitle = null;
        if (input.DestinationId is { } destinationId)
        {
            destinationTitle = await db.Destinations
                .Where(d => d.Id == destinationId)
                .Select(d => d.Translations.FirstOrDefault(t => t.Locale == input.PreferredLocale) ?? d.Translations.FirstOrDefault())
                .Select(t => t!.Title)
                .FirstOrDefaultAsync(cancellationToken);
        }

        string? offerTitle = null;
        if (input.OfferId is { } offerId)
        {
            offerTitle = await db.Offers
                .Where(o => o.Id == offerId)
                .Select(o => o.Translations.FirstOrDefault(t => t.Locale == input.PreferredLocale) ?? o.Translations.FirstOrDefault())
                .Select(t => t!.Title)
                .FirstOrDefaultAsync(cancellationToken);
        }

        var travelRequest = new TravelRequest(
            input.LastName, input.FirstName, input.MiddleName, input.Phone, input.PreferredLocale,
            input.PassengersAdults, input.PassengersChildren, input.ChildrenAges, input.Message,
            input.DepartureDate, input.ReturnDate,
            input.DestinationId, destinationTitle, input.OfferId, offerTitle,
            input.PassportPhotoPaths,
            input.SourceUtm, request.SourceIp, input.SourceLocale);

        db.TravelRequests.Add(travelRequest);
        await db.SaveChangesAsync(cancellationToken);

        // Best-effort staff notification — a failed/unconfigured mail provider must never fail
        // the request itself, since the request is already durably saved above by this point.
        try
        {
            var notifyTo = notificationSettings.Value.NotifyTo;
            if (!string.IsNullOrWhiteSpace(notifyTo))
                await emailService.SendAsync(notifyTo, BuildSubject(travelRequest), BuildHtmlBody(travelRequest, notificationSettings.Value.AdminUrl), cancellationToken);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to send new-travel-request notification email for request {TravelRequestId}", travelRequest.Id);
        }

        return Result.Success(travelRequest.Id);
    }

    private static string BuildSubject(TravelRequest travelRequest)
        => $"Новая заявка: {travelRequest.LastName} {travelRequest.FirstName}".Trim();

    private static string BuildHtmlBody(TravelRequest travelRequest, string? adminUrl)
    {
        var fullName = string.Join(' ', new[] { travelRequest.LastName, travelRequest.FirstName, travelRequest.MiddleName }
            .Where(part => !string.IsNullOrWhiteSpace(part)));
        var direction = travelRequest.OfferSnapshotTitle ?? travelRequest.DestinationSnapshotTitle;
        var dates = travelRequest.ReturnDate is { } returnDate
            ? $"{travelRequest.DepartureDate:dd.MM.yyyy} — {returnDate:dd.MM.yyyy}"
            : $"{travelRequest.DepartureDate:dd.MM.yyyy}";

        var sb = new StringBuilder();
        sb.Append("<h2>Новая заявка на подбор авиабилета</h2>");
        sb.Append("<table cellpadding=\"4\" cellspacing=\"0\">");
        AppendRow(sb, "Имя", WebUtility.HtmlEncode(fullName));
        AppendRow(sb, "Телефон", WebUtility.HtmlEncode(travelRequest.Phone));
        if (!string.IsNullOrWhiteSpace(direction))
            AppendRow(sb, "Направление", WebUtility.HtmlEncode(direction));
        AppendRow(sb, "Даты", WebUtility.HtmlEncode(dates));
        AppendRow(sb, "Взрослые", travelRequest.PassengersAdults.ToString());
        AppendRow(sb, "Дети", travelRequest.PassengersChildren.ToString());
        if (!string.IsNullOrWhiteSpace(travelRequest.Message))
            AppendRow(sb, "Сообщение", WebUtility.HtmlEncode(travelRequest.Message));
        sb.Append("</table>");

        if (!string.IsNullOrWhiteSpace(adminUrl))
        {
            var link = $"{adminUrl.TrimEnd('/')}/admin/travel-requests/{travelRequest.Id}";
            sb.Append($"<p><a href=\"{link}\">Открыть заявку в CRM</a></p>");
        }

        return sb.ToString();
    }

    private static void AppendRow(StringBuilder sb, string label, string value)
        => sb.Append($"<tr><td><strong>{WebUtility.HtmlEncode(label)}</strong></td><td>{value}</td></tr>");
}
